#!/bin/bash

#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


${ANDROID_BUILD_TOP}/prebuilts/android-emulator/linux-x86_64/qemu/linux-x86_64/qemu-system-aarch64 \
  -M vexpress-a9 \
  -m 1024M \
  -kernel ${ANDROID_PRODUCT_OUT}/kernel \
  -append "console=ttyAMA0 root=/dev/ram androidboot.hardware=brillo qemu=1 androidboot.selinux=enforcing" \
  -nographic \
  -initrd ${ANDROID_PRODUCT_OUT}/ramdisk.img \
  -device virtio-scsi-device,id=scsi \
  -device scsi-hd,drive=system \
  -drive file="${ANDROID_PRODUCT_OUT}/system.img,if=none,id=system,format=raw" \
  -device scsi-hd,drive=userdata \
  -drive file="${ANDROID_PRODUCT_OUT}/userdata.img,if=none,id=userdata,format=raw" \
  -redir tcp:5555::5555 \
  -dtb ${ANDROID_PRODUCT_OUT}/kernel-dtb
