#!/bin/bash

#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

function PrintUsage() {
  echo "$0 -m <mem>"
  echo -e "\t-m <mem>\tSet memory size in MB"
  exit 1
}

MEM=1024
ARGS=$(getopt -o hm: -- "$@")
eval set -- "$ARGS"
while true ; do
   case "$1" in
     -m)
        case "$2" in
          *) MEM=$2; shift 2;;
        esac ;;
     -h) PrintUsage ;;
     --) shift; break ;;
   esac
done

echo Starting emulator with ${MEM}MB memory
exec \
${ANDROID_BUILD_TOP}/prebuilts/android-emulator/linux-x86_64/qemu/linux-x86_64/qemu-system-aarch64 \
  -M vexpress-a9 \
  -m ${MEM}M \
  -kernel ${ANDROID_BUILD_TOP}/out/target/product/brilloemulator_arm/kernel \
  -append "console=ttyAMA0 ro root=/dev/sda androidboot.hardware=qemu qemu=1 rootwait noinitrd init=/init androidboot.selinux=enforcing" \
  -nographic \
  -device virtio-scsi-device,id=scsi \
  -device scsi-hd,drive=system \
  -drive file="${ANDROID_BUILD_TOP}/out/target/product/brilloemulator_arm/system.img,if=none,id=system,format=raw" \
  -device scsi-hd,drive=userdata \
  -drive file="${ANDROID_BUILD_TOP}/out/target/product/brilloemulator_arm/userdata.img,if=none,id=userdata,format=raw" \
  -redir tcp:5555::5555 \
  -dtb ${ANDROID_BUILD_TOP}/out/target/product/brilloemulator_arm/kernel-dtb
