#!/system/bin/sh -e
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Expected WiFi interface names.
client_interface="wlan0"
ap_interface="softap.0"

# Device parameter for getting / setting serial number.
serial_number_ctrl="/sys/devices/soc.0/a000000.qcom,wcnss-wlan/serial_number"

# Default value of the serial number at boot.
default_serial_number="00000000"

# Property to retrieve via "getprop" in order to get the device serial number.
serial_number_property="ro.boot.serialno"

startup_wcnss () {
  # Loads the WiFi peripheral.  This is a no-op if performed before.
  set_serial_number
  echo 1 > /dev/wcnss_wlan || true
}

startup_wifi () {
  # Starts up WiFi in mode |mode|, which can be "ap" or "client".  Returns
  # the interface name that was created.
  startup_wcnss
  local mode="$1"
  local con_mode
  local interface
  case "$mode" in
    ap)
      con_mode=1
      interface="${ap_interface}"
      ;;
    client)
      con_mode=0
      interface="${client_interface}"
      ;;
    *)
      echo "Invalid mode $mode"
      return 1
  esac
  if [ -e "/sys/class/net/$interface" ] ; then
    echo "${interface}"
    return 0
  fi
  for tries in 1 2 3 4 5 ; do
    # Although we are supposed to be setting the mode to $mode, we've seen this
    # toggle the interface state through different modes instead.  The "echo"
    # should be blocked while the kernel reconfigures the device so there is
    # no need to sleep before checking.
    echo "$con_mode" > /sys/module/wlan/parameters/con_mode
    if [ -e "/sys/class/net/$interface" ] ; then
      echo "${interface}"
      return 0
    fi
  done
  echo "Interface $interface never appeared."
  return 1
}

set_serial_number () {
  # Make sure the qcom wireless driver has a non-default serial number so
  # we all don't have the same MAC address.
  local serial_number=$(cat "${serial_number_ctrl}")

  if [ "${serial_number}" != "${default_serial_number}" ] ; then
    # Serial number already set.
    return 0
  fi

  # Retrieve the serial number out of ROM and supply it to the wireless driver.
  getprop "${serial_number_property}" > "${serial_number_ctrl}"
}
